environment:
    OPENSSL_INCLUDE_DIR: C:\OpenSSL-Win64\include
    OPENSSL_LIB_DIR: C:\OpenSSL-Win64\lib
    OPENSSL_LIBS: ssleay32:libeay32

cache:
    - 'C:\Users\appveyor\.cargo'

install:
    - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.exe'
    - rust-nightly-x86_64-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
    - SET PATH=%PATH%;C:\Program Files\Rust\bin;C:\msys64\mingw64\bin;C:\OpenSSL-Win64
    - cc --version
    - gcc --version
    - rustc -V
    - cargo -V
    - nuget install redis-64 -excludeversion
    - redis-64\tools\redis-server.exe --service-install
    - redis-64\tools\redis-server.exe --service-start

build: false

test_script:
    - cd vol1
    - cargo build
    - cargo run --bin=lesson2
    - cargo run --bin=lesson3
#    - cargo run --bin=lesson4
    - cargo run --bin=lesson5
    - cargo run --bin=lesson6
    - cargo run --bin=lesson7
    - cargo run --bin=lesson9
    - cargo run --bin=lesson10
    - cargo run --bin=lesson11
    - cargo run --bin=lesson12
    - cargo run --bin=lesson13
    - cargo run --bin=lesson14
    - cargo run --bin=lesson17
    - cargo run --bin=lesson18
    - cargo run --bin=lesson20
    - cargo run --bin=lesson21
    - cd ..\vol2
    - cargo build
    - cargo run --bin=lesson2
    - cargo run --bin=lesson3
    - cargo run --bin=lesson4
    - cargo run --bin=lesson5
    - cargo run --bin=lesson6
    - cargo run --bin=lesson7
    - cargo run --bin=lesson8
    - cargo run --bin=lesson10
    - cargo run --bin=lesson11
    - cargo run --bin=lesson12
    - cargo run --bin=lesson13
    - cargo run --bin=lesson14
    - cargo run --bin=lesson15
    - cargo run --bin=lesson16
    - cargo run --bin=lesson17
    - cargo run --bin=lesson18 || ver>nul
    - cargo run --bin=lesson19
    - cargo run --bin=lesson20
    - cargo run --bin=lesson21
